### ISSUE TITLE
Manjaro: System tray icon will not always properly render

### ISSUE THREAD

**Issue by asorel1942** [Lightcord/Lightcord#19] opened 2020-08-11 14:05 UTC
Lightcord system tray entry on Manjaro KDE will occasionally take the appearance seen in the attached screenshot rather than the proper one. Exact cause uncertain, so far it has been observed after rebooting the system and after ~7 hours of idle time. Quitting Lightcord and reopening it solves the issue.
![image](https://user-images.githubusercontent.com/33983895/89907056-2a66c680-dbba-11ea-8573-ec0d9e8faff4.png)

**Comment by phorcysed** [comment] 2020-08-11 14:07
this would probably be caused by some swap on your hard drive, I had this issue myself with other programs (on XFCE)

**Comment by asorel1942** [comment] 2020-08-11 14:15
> this would probably be caused by some swap on your hard drive, I had this issue myself with other programs (on XFCE)
How did you end up solving it? Do I have to repartition my boot drive to re-create the swap?

**Comment by phorcysed** [comment] 2020-08-11 14:54
I fucked up my system between that, didn't add a swap at that time.
but this isn't a BIG/breaking issue so i'm gonna close it

**Closed by phorcysed** 2020-08-11 14:54 UTC
