### ISSUE TITLE
[BUG] Edit Pluginsettings

### ISSUE THREAD

**Issue by FeelsBadMan1** [Lightcord/Lightcord#212] opened 2021-03-11 09:57 UTC
**Describe the bug**
If i add Plugins that are not offically released by BetterDiscord like Accountswicher, Animated Status & more then try to edit settings so i press on the Settings button then what happens is it disappear from the Pluginlist and print "Component Error" in Black Text instead. If i then choose another tab like Themes and then go back to Plugins the Plugin is shown again but the same happens if i press on the "Settings" Button again.

**To Reproduce**
1. Go to 'Usersettings -> Plugins'
2. Click on 'any unofficial Plugin (Accountswitcher, Animated Status etc.)'
3. Scroll down to ' Settings'
4. See the error "Component Error"

**Expected behavior**
I expected that it works usually and i can edit settings like it should work but i get the error instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/40109798/110769344-5cc3c980-8258-11eb-9d2b-8a8bd2c8fdfd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [v0.5]

**Comment by Titaniumtown** [comment] 2021-03-11 14:51
> Esit pluginsettings

I think you may have a typo there.

**Comment by FeelsBadMan1** [comment] 2021-03-11 15:25
hmm. what do you mean exactly and how do i solve it?

**Comment by C0D3-M4513R** [comment] 2021-03-13 07:40
The settings button of `Accountswitcher` works perfectly fine for me on Lightcord v0.1.4.

**Comment by FeelsBadMan1** [comment] 2021-03-23 16:42
For me all Plugins that giv the component error are working fine on enhancedDiscord so the issure is somewhere in lightcord cause it works on Betterdiscord & EnchancedDiscord

**Comment by vbajs** [comment] 2021-03-23 17:04
The issue is that lightcord is using an outdated version of BandagedBetterDiscord.
Either fully switch to BetterDiscord or wait until the Devs update BangedBetterDiscord. I do not recommend switching to EnhancedDiscord as it is EOL.

**Comment by ribkix** [comment] 2021-04-09 21:31
I can confirm that this is happening to me too.

**Comment by smartfrigde** [comment] 2021-06-04 18:16
Fixed by latest commits

**Closed by smartfrigde** 2021-06-04 18:16 UTC
Labels: bug
