### ISSUE TITLE
[BUG] Some plugins don't work

### ISSUE THREAD

**Issue by Nermal242** [Lightcord/Lightcord#190] opened 2021-02-19 19:30 UTC
**Describe the bug**
Some plugins won't work and gives an error, disabling Plugin Scanning won't work either. For example FriendNotifications won't work due to it shows an error when opening the settings thing on the plugins tab.
**To Reproduce**
1. Go to 'User Settings - Plugins'
2. Click on the settings thing for some plugins that should work in normal BetterDiscord, example FriendNotifications.plugin.
3. See error

**Expected behavior**
It should open up a settings popup and it should work.
**Screenshots**
![image](https://user-images.githubusercontent.com/56689711/108551872-d4a17280-72f0-11eb-852b-133db253067b.png)
![image](https://user-images.githubusercontent.com/56689711/108551910-e08d3480-72f0-11eb-90db-4de1415fbcaa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by orangemn6** [comment] 2021-02-25 23:59
That is not a lightcord error, that is the plugin. Contact the plugin developer.

**Comment by Nermal242** [comment] 2021-02-26 00:30
On the normal discord it works fine.

**Comment by sitiom** [comment] 2021-03-19 00:10
Duplicate of #212 (Although this was opened first).

**Comment by smartfrigde** [comment] 2021-06-04 18:09
Fixed

**Closed by smartfrigde** 2021-06-04 18:09 UTC
Labels: bug
