### ISSUE TITLE
[BUG] "Account Info" in settings crashes Lightcord

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [Lightcord/Lightcord#48] opened 2020-09-26 09:49 UTC
**Describe the bug**
"Account Info" in settings crashes Lightcord.

**To Reproduce**
1. Go into settings
2. Click on Account Info

**Expected behavior**
A settings window with (presumably) your account information should appear.

**Screenshots**
[Video](https://streamable.com/rc0jvi)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.1.4

**Comment by unixkeys** [comment] 2020-09-26 10:41
Duplicate of #37, #32 and #20
but I think this is fixed in master and it will be in next release

**Closed by unixkeys** 2020-09-26 10:41 UTC
Labels: bug
