### ISSUE TITLE
[BUG] Betterdiscord shat itself

### ISSUE THREAD

**Issue by Empelton** [Lightcord/Lightcord#58] opened 2020-10-15 16:30 UTC
**Describe the bug**
So basically whenever I try to load lightcord with BD it gives an error and doesn't allow me to enable or disable plugins.
**To Reproduce**
1. Just use my Operating System
2. Open Lightcord with BetterDiscord enabled.

**Expected behavior**
Well you should just see down below on Screenshots.
**Screenshots**
![image](https://user-images.githubusercontent.com/70936861/96158645-03a77200-0f14-11eb-9e8b-d1a8d8878d79.png)

**Desktop (please complete the following information):**
 - **OS:** Windows Super Lite using Windows 10 pro, Version 2004, Build 19041.572
- **Video of what WSL is:** https://www.youtube.com/watch?v=YQfoyzQjAPc

**Additional context**
I can't really figure out  what causes this to happen. Might update if reinstalling any sort of **drivers** helps.

**Comment by JeanOUINA** [comment] 2020-10-15 16:31
duplicate of #54

**Closed by JeanOUINA** 2020-10-15 16:31 UTC
Labels: bug
