### ISSUE TITLE
[BUG] Don't work on mac 

### ISSUE THREAD

**Issue by Elie404** [Lightcord/Lightcord#313] opened 2021-07-24 10:36 UTC
**Describe the bug**
When I launch the application it says Unable to open the Lightcord application.

**To Reproduce**
1. I dezip the file
2. I move the file to the Application folder
3. I open the app (double tap)

**Expected behavior**
That the application launches. 

**Screenshots**

**Desktop (please complete the following information):**
MacOS Catalina 10.15.7

**Additional context**
![image](https://user-images.githubusercontent.com/79168733/126865895-0fe1bed0-57c5-4170-8230-77c9e77ce3ab.png)

**Comment by JeanOUINA** [comment] 2021-07-24 11:25
duplicate of #273 problem 6

**Closed by JeanOUINA** 2021-07-24 11:25 UTC
Labels: bug
